#!/bin/bash

function createPatient() {
  infoln "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/patient.scm.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/patient.scm.com/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:7054 --caname ca-patient --tls.certfiles "${PWD}/organizations/fabric-ca/patient/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-patient.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-patient.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-patient.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-patient.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/patient.scm.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy patient's CA cert to patient's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/patient.scm.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/patient/ca-cert.pem" "${PWD}/organizations/peerOrganizations/patient.scm.com/msp/tlscacerts/ca.crt"

  # Copy patient's CA cert to patient's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/patient.scm.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/patient/ca-cert.pem" "${PWD}/organizations/peerOrganizations/patient.scm.com/tlsca/tlsca.patient.scm.com-cert.pem"

  # Copy patient's CA cert to patient's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/patient.scm.com/ca"
  cp "${PWD}/organizations/fabric-ca/patient/ca-cert.pem" "${PWD}/organizations/peerOrganizations/patient.scm.com/ca/ca.patient.scm.com-cert.pem"

  infoln "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-patient --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/patient/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering user"
  set -x
  fabric-ca-client register --caname ca-patient --id.name user0 --id.secret user0pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/patient/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-patient --id.name patientadmin --id.secret patientadminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/patient/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:7054 --caname ca-patient -M "${PWD}/organizations/peerOrganizations/patient.scm.com/peers/peer0.patient.scm.com/msp" --csr.hosts peer0.patient.scm.com --tls.certfiles "${PWD}/organizations/fabric-ca/patient/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/patient.scm.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/patient.scm.com/peers/peer0.patient.scm.com/msp/config.yaml"

  infoln "Generating the peer0-tls certificates"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:7054 --caname ca-patient -M "${PWD}/organizations/peerOrganizations/patient.scm.com/peers/peer0.patient.scm.com/tls" --enrollment.profile tls --csr.hosts peer0.patient.scm.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/patient/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/patient.scm.com/peers/peer0.patient.scm.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/patient.scm.com/peers/peer0.patient.scm.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/patient.scm.com/peers/peer0.patient.scm.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/patient.scm.com/peers/peer0.patient.scm.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/patient.scm.com/peers/peer0.patient.scm.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/patient.scm.com/peers/peer0.patient.scm.com/tls/server.key"

  infoln "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user0:user0pw@localhost:7054 --caname ca-patient -M "${PWD}/organizations/peerOrganizations/patient.scm.com/users/User1@patient.scm.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/patient/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/patient.scm.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/patient.scm.com/users/User1@patient.scm.com/msp/config.yaml"

  infoln "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://patientadmin:patientadminpw@localhost:7054 --caname ca-patient -M "${PWD}/organizations/peerOrganizations/patient.scm.com/users/Admin@patient.scm.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/patient/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/patient.scm.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/patient.scm.com/users/Admin@patient.scm.com/msp/config.yaml"
}

function createDoctor() {
  infoln "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/doctor.scm.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/doctor.scm.com/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:7064 --caname ca-doctor --tls.certfiles "${PWD}/organizations/fabric-ca/doctor/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-7064-ca-doctor.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-7064-ca-doctor.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-7064-ca-doctor.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-7064-ca-doctor.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/doctor.scm.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy doctor's CA cert to doctor's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/doctor.scm.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/doctor/ca-cert.pem" "${PWD}/organizations/peerOrganizations/doctor.scm.com/msp/tlscacerts/ca.crt"

  # Copy doctor's CA cert to doctor's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/doctor.scm.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/doctor/ca-cert.pem" "${PWD}/organizations/peerOrganizations/doctor.scm.com/tlsca/tlsca.doctor.scm.com-cert.pem"

  # Copy doctor's CA cert to doctor's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/doctor.scm.com/ca"
  cp "${PWD}/organizations/fabric-ca/doctor/ca-cert.pem" "${PWD}/organizations/peerOrganizations/doctor.scm.com/ca/ca.doctor.scm.com-cert.pem"

  infoln "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-doctor --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/doctor/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering user"
  set -x
  fabric-ca-client register --caname ca-doctor --id.name user0 --id.secret user0pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/doctor/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-doctor --id.name doctoradmin --id.secret doctoradminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/doctor/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:7064 --caname ca-doctor -M "${PWD}/organizations/peerOrganizations/doctor.scm.com/peers/peer0.doctor.scm.com/msp" --csr.hosts peer0.doctor.scm.com --tls.certfiles "${PWD}/organizations/fabric-ca/doctor/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/doctor.scm.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/doctor.scm.com/peers/peer0.doctor.scm.com/msp/config.yaml"

  infoln "Generating the peer0-tls certificates"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:7064 --caname ca-doctor -M "${PWD}/organizations/peerOrganizations/doctor.scm.com/peers/peer0.doctor.scm.com/tls" --enrollment.profile tls --csr.hosts peer0.doctor.scm.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/doctor/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/doctor.scm.com/peers/peer0.doctor.scm.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/doctor.scm.com/peers/peer0.doctor.scm.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/doctor.scm.com/peers/peer0.doctor.scm.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/doctor.scm.com/peers/peer0.doctor.scm.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/doctor.scm.com/peers/peer0.doctor.scm.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/doctor.scm.com/peers/peer0.doctor.scm.com/tls/server.key"

  infoln "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user0:user0pw@localhost:7064 --caname ca-doctor -M "${PWD}/organizations/peerOrganizations/doctor.scm.com/users/User1@doctor.scm.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/doctor/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/doctor.scm.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/doctor.scm.com/users/User1@doctor.scm.com/msp/config.yaml"

  infoln "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://doctoradmin:doctoradminpw@localhost:7064 --caname ca-doctor -M "${PWD}/organizations/peerOrganizations/doctor.scm.com/users/Admin@doctor.scm.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/doctor/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/doctor.scm.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/doctor.scm.com/users/Admin@doctor.scm.com/msp/config.yaml"
}


function createOrderer() {
  infoln "Enrolling the CA admin"
  mkdir -p organizations/ordererOrganizations/scm.com

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/ordererOrganizations/scm.com

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:9054 --caname ca-orderer --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/ordererOrganizations/scm.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy orderer org's CA cert to orderer org's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/ordererOrganizations/scm.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem" "${PWD}/organizations/ordererOrganizations/scm.com/msp/tlscacerts/tlsca.scm.com-cert.pem"

  # Copy orderer org's CA cert to orderer org's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/ordererOrganizations/scm.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem" "${PWD}/organizations/ordererOrganizations/scm.com/tlsca/tlsca.scm.com-cert.pem"

  infoln "Registering orderer"
  set -x
  fabric-ca-client register --caname ca-orderer --id.name orderer --id.secret ordererpw --id.type orderer --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering the orderer admin"
  set -x
  fabric-ca-client register --caname ca-orderer --id.name ordererAdmin --id.secret ordererAdminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Generating the orderer msp"
  set -x
  fabric-ca-client enroll -u https://orderer:ordererpw@localhost:9054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/scm.com/orderers/orderer.scm.com/msp" --csr.hosts orderer.scm.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/ordererOrganizations/scm.com/msp/config.yaml" "${PWD}/organizations/ordererOrganizations/scm.com/orderers/orderer.scm.com/msp/config.yaml"

  infoln "Generating the orderer-tls certificates"
  set -x
  fabric-ca-client enroll -u https://orderer:ordererpw@localhost:9054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/scm.com/orderers/orderer.scm.com/tls" --enrollment.profile tls --csr.hosts orderer.scm.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the orderer's tls directory that are referenced by orderer startup config
  cp "${PWD}/organizations/ordererOrganizations/scm.com/orderers/orderer.scm.com/tls/tlscacerts/"* "${PWD}/organizations/ordererOrganizations/scm.com/orderers/orderer.scm.com/tls/ca.crt"
  cp "${PWD}/organizations/ordererOrganizations/scm.com/orderers/orderer.scm.com/tls/signcerts/"* "${PWD}/organizations/ordererOrganizations/scm.com/orderers/orderer.scm.com/tls/server.crt"
  cp "${PWD}/organizations/ordererOrganizations/scm.com/orderers/orderer.scm.com/tls/keystore/"* "${PWD}/organizations/ordererOrganizations/scm.com/orderers/orderer.scm.com/tls/server.key"

  # Copy orderer org's CA cert to orderer's /msp/tlscacerts directory (for use in the orderer MSP definition)
  mkdir -p "${PWD}/organizations/ordererOrganizations/scm.com/orderers/orderer.scm.com/msp/tlscacerts"
  cp "${PWD}/organizations/ordererOrganizations/scm.com/orderers/orderer.scm.com/tls/tlscacerts/"* "${PWD}/organizations/ordererOrganizations/scm.com/orderers/orderer.scm.com/msp/tlscacerts/tlsca.scm.com-cert.pem"

  infoln "Generating the admin msp"
  set -x
  fabric-ca-client enroll -u https://ordererAdmin:ordererAdminpw@localhost:9054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/scm.com/users/Admin@scm.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/ordererOrganizations/scm.com/msp/config.yaml" "${PWD}/organizations/ordererOrganizations/scm.com/users/Admin@scm.com/msp/config.yaml"
}
